import { readFileSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";
import assert from "node:assert/strict";

const indexHtml = readFileSync(join(process.cwd(), "index.html"), "utf8");
const faviconSvg = readFileSync(join(process.cwd(), "public", "favicon.svg"), "utf8");
const morganBankLogo = readFileSync(join(process.cwd(), "public", "morgan-bank-logo.webp"));
const lutherAiLogo = readFileSync(join(process.cwd(), "public", "luther-ai-logo.png"));

function assertCompleteWebp(bytes) {
  assert.equal(bytes.subarray(0, 4).toString("ascii"), "RIFF", "logo must be a RIFF file");
  assert.equal(bytes.subarray(8, 12).toString("ascii"), "WEBP", "logo must be a WebP file");
  assert.equal(
    bytes.readUInt32LE(4) + 8,
    bytes.length,
    "logo byte length must match its RIFF header"
  );

  let offset = 12;
  let imageChunkFound = false;
  while (offset < bytes.length) {
    assert.ok(offset + 8 <= bytes.length, "logo must contain a complete WebP chunk header");
    const chunkType = bytes.subarray(offset, offset + 4).toString("ascii");
    const chunkSize = bytes.readUInt32LE(offset + 4);
    const paddedChunkEnd = offset + 8 + chunkSize + (chunkSize % 2);
    assert.ok(paddedChunkEnd <= bytes.length, `${chunkType} chunk must not be truncated`);
    imageChunkFound ||= ["VP8 ", "VP8L", "VP8X"].includes(chunkType);
    offset = paddedChunkEnd;
  }

  assert.equal(offset, bytes.length, "logo chunks must consume the complete WebP file");
  assert.equal(imageChunkFound, true, "logo must contain a WebP image chunk");
}

test("external Morgan Bank logo is a complete, internally consistent WebP", () => {
  assertCompleteWebp(morganBankLogo);
  assert.ok(morganBankLogo.length <= 15_000, "Morgan Bank logo must remain compact");
  assert.match(
    indexHtml,
    /<img class="center-logo" src="\/morgan-bank-logo\.webp" width="900" height="501" alt="Morgan Bank logo">/,
    "the hero must request the cacheable external logo with intrinsic dimensions"
  );
  assert.doesNotMatch(indexHtml, /data:image\/webp;base64,/, "the hero logo must not remain in JavaScript");
});

test("logo integrity check rejects the demonstrated two-character data loss", () => {
  const intact = morganBankLogo.toString("base64");
  const historicalRepairPoint = "WhkgUzSdE3";
  assert.ok(intact.includes(historicalRepairPoint), "test fixture must contain the repaired bytes");
  const truncated = intact.replace(historicalRepairPoint, "WhkgSdE3");

  assert.throws(() => assertCompleteWebp(Buffer.from(truncated, "base64")), assert.AssertionError);
});

test("the document links a Morgan Bank favicon instead of the stock Vite mark", () => {
  assert.match(
    indexHtml,
    /<link rel="icon" type="image\/svg\+xml" href="\/favicon\.svg" \/>/,
    "index.html must explicitly link the favicon Safari and other browsers should request"
  );
  assert.match(faviconSvg, /<title>Morgan Bank<\/title>/);
  assert.match(faviconSvg, /#12323a/i, "favicon must use the Morgan Bank dark brand color");
  assert.match(faviconSvg, /#5ec7c2/i, "favicon must use the Morgan Bank teal brand color");
  assert.doesNotMatch(
    faviconSvg,
    /#863bff|#7e14ff|#47bfff|vite/i,
    "stock Vite branding must not remain"
  );
});

test("signed-in pages include one concise, responsive Luther AI credit", () => {
  const gateStart = indexHtml.indexOf(
    '      if (isTeacher || (screen === "student" && student)) {'
  );
  const gateEnd = indexHtml.indexOf(
    '\n      document.getElementById("app").innerHTML = html;',
    gateStart
  );
  assert.notEqual(gateStart, -1, "the authenticated-page credit gate must exist");
  assert.notEqual(gateEnd, -1, "the authenticated-page credit gate must end before rendering");
  const authenticatedCreditGate = indexHtml.slice(gateStart, gateEnd);

  const creditMarkup = [
    '<footer class="luther-ai-credit" aria-label="AI insights credit">',
    '<img src="/luther-ai-logo.png" alt="" aria-hidden="true" />',
    '<span>AI content is generated by <strong>Luther AI</strong>.</span>',
  ];

  for (const markup of creditMarkup) {
    assert.equal(
      indexHtml.split(markup).length - 1,
      1,
      `index.html must contain exactly one ${markup}`
    );
    assert.ok(
      authenticatedCreditGate.includes(markup),
      `${markup} must remain inside the authenticated teacher/student gate`
    );
  }
  assert.match(authenticatedCreditGate, /html \+= `[\s\S]*?<footer class="luther-ai-credit"/);
  assert.match(indexHtml, /\.luther-ai-credit \{[\s\S]*?justify-content: flex-end;/);
  assert.match(indexHtml, /@media \(max-width: 700px\) \{[\s\S]*?\.luther-ai-credit \{ justify-content: center; \}/);
  assert.match(indexHtml, /@media print \{[\s\S]*?\.luther-ai-credit \{ display: none; \}/);
});

test("Luther AI credit uses the compact, complete Luther AI logo asset", () => {
  const pngSignature = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

  assert.equal(lutherAiLogo.subarray(0, 8).compare(pngSignature), 0, "logo must be a PNG");
  assert.equal(lutherAiLogo.readUInt32BE(16), 56, "logo source must be 56 pixels wide");
  assert.equal(lutherAiLogo.readUInt32BE(20), 56, "logo source must be 56 pixels tall");
  assert.ok(lutherAiLogo.length <= 6_000, "logo must remain smaller than 6 KB");
  assert.match(
    indexHtml,
    /\.luther-ai-credit img \{[\s\S]*?width: 28px;[\s\S]*?height: 28px;/,
    "the high-density logo source must render at an unobtrusive Luther AI size"
  );
});
